- name: 🌃 Mode Nuit
  description: Configuration automatique pour le mode nuit
  triggers:
    - at_time: '22:00'
  actions:
    - notify: Activation du mode nuit
    - kill: discord.exe
    - launch: notepad.exe
  cooldown: 3600
  enabled: true
- name: ⚡ CPU Surchargé
  description: Actions d'urgence quand le CPU est surchargé
  triggers:
    - cpu_above: 90
  actions:
    - notify: CPU surchargé - fermeture d'applications
    - kill: chrome.exe
    - wait: 2
    - notify: Optimisation terminée
  cooldown: 180
  enabled: true
- name: 🌐 Ouverture Navigation
  description: Ouvre les sites favoris au démarrage
  triggers:
    - app_start: chrome.exe
  actions:
    - wait: 5
    - open_url: https://github.com
    - open_url: https://stackoverflow.com
    - notify: Sites favoris ouverts
  cooldown: 900
  enabled: true
